# Generated by Django 6.1 on 2026-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_savedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismplace',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
