# Generated by Django 6.1 on 2026-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='specialties',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
